# Generated by Django 5.2.5 on 2025-08-14 10:41

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('cart_name', models.CharField(max_length=120)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('store_name', models.CharField(
                    blank=True, default='', max_length=120)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('notes', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, null=True)),
                ('items_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal(
                    '0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('idempotency_key', models.CharField(blank=True,
                 db_index=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['completed_at'], name='cart_purcha_complet_be23bf_idx'), models.Index(fields=['store_name'], name='cart_purcha_store_n_19a861_idx')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[
                 django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantity', models.PositiveIntegerField(
                    validators=[django.core.validators.MinValueValidator(1)])),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('brand', models.CharField(blank=True, default='', max_length=64)),
                ('barcode', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.purchase')),
            ],
            options={
                'indexes': [models.Index(fields=['purchase'], name='cart_purcha_purchas_c97010_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='item_unit_price_non_negative'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='item_quantity_at_least_one')],
            },
        ),
    ]
