# Generated by Django 5.2.5 on 2025-08-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_purchase_user_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE cart_purchaseitem DROP COLUMN IF EXISTS category;",
            "ALTER TABLE cart_purchaseitem ADD COLUMN category varchar(120) NULL;"
        )
    ]
