# Generated by Django 5.2.5 on 2025-08-15 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_purchase_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchase',
            name='unique_idempotency_per_user',
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False), models.Q(('idempotency_key', ''), _negated=True)), fields=('user', 'idempotency_key'), name='unique_idempotency_per_user'),
        ),
    ]
