# Generated by Django 5.2.5 on 2025-08-15 19:52

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_purchase_unique_idempotency_per_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CNY', 'CNY'), ('JPY', 'JPY'), ('GBP', 'GBP'), ('INR', 'INR'), ('BRL', 'BRL'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('MXN', 'MXN'), ('KRW', 'KRW'), ('TRY', 'TRY'), ('ZAR', 'ZAR')], db_index=True, default='EUR', max_length=3, validators=[django.core.validators.RegexValidator(message='Currency must be a 3-letter ISO 4217 code (uppercase).', regex='^[A-Z]{3}$')]),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('items_count__gte', 0)), name='purchase_items_count_non_negative'),
        ),
    ]
